![logo do programa](http://www.ppgaig.iciag.ufu.br/sites/ppgaig.iciag.ufu.br/files/imagens/logo-ppgaig.png)

<b><center> PREDIÇÃO DA PRODUTIVIDADE DE SOJA OBTIDO POR TÉCNICAS DE REDES NEURAIS MULTICAMADAS E RECOMENDAÇÃO DE ADUBAÇÃO E CALAGEM NA REGIÃO DO ALTO PARANAIBA-MG </center></b>
<br></br>

Instituição: Universidade Federal de Uberlândia (UFU).

Disciplina: Mineração de dados.

Docente: Prof. Dr. Murillo Guimarães Carneiro.

Discente:  Dário da Silva Melo.

Curso: Mestrado Acadêmico em Agricultura e Informações Geoespaciais

<br></br>
<b><center>MONTE CARMELO-MG</center></b>
<b><center>2023</center></b>

<br></br>
<b><center>Rede Neural Artificial desenvolvida em linguagem Python.</center></b>
<br></br>

In [ ]:
from sklearn import preprocessing
import numpy as np


Biblioteca do python para trabalhar com processamento científico.

In [7]:
def sigmoid(soma):
    return 1 / (1 + np.exp(-soma))

É a função que ativa o neurônio.

Função sigmoide: y = 1 / (1 + e ^ -x)

e = número de Euler = 2.718281828459045

x = soma ( somatório dos produtos entre os dados de entrada e o seu peso).

np.exp é a função exponecial do numpy que eleva o numero de Euler (e) a "-x"(soma).

A função sigmoide retorna valores entre 0 e 1 (não retorna valores negativos).

Se x for alto o valor será aproximadamente 1.

Se x for pequeno o valor será aproximadamente 0.

In [3]:
def derivadaParcial(valor_sigmoide):
    return valor_sigmoide * ( 1 - valor_sigmoide )

A função tem como objetivo calcular o declive da curva do erro, mostrando a melhor orienção a seguir para ajustar os pesos e diminuir o erro na rede neural (atigir o mínimo global)

sigmoide: y = 1 / (1 + e ^ -x)

derivada: d = y * (1 - y)

In [97]:
entradas = np.array([[0,0], [0,1], [1,0], [1,1]])
respostas_esperadas = np.array([[0],[1],[1],[0]])

A variavel "entrada" (matriz) contém os dados de entrada "x1" e "x2". A variaval "resposta_esperada" (matriz) é valor da "classe" para determinado dado de entrada  "x1" e "x2".

|x1 x2| -> classe
<BR>| 0 0 | -> 0</BR>
| 0 1 | -> 1
<BR>| 1 0 | -> 1</BR>
| 1 1 | -> 0

In [98]:
pesos_x1_x2 = np.array([[-0.424,-0.740,-0.961], [0.358,-0.577,-0.469]])

A variavel "pesos_x1_x2" (matriz) contém os pesos de ligação das variaveis "x1" e "x2" para os neurônios da camada oculta. Os valores inicais de pesos (W) foram obtidos de forma aleatória.

x1 ------(sinapse/peso W ( x1, neurônio 01 = w11 = -0.424)------>
<BR>x1 ------(sinapse/peso W ( x1, neurônio 02 = w12 = -0.740)------></BR>
x1-------(sinapse/peso W ( x1, neurônio 03 = w13 = -0.961)------>

x2 ------(sinapse/peso W ( x2, neurônio 01 = w21 = 0.358)------>
<BR>x2 ------(sinapse/peso W( x2, neurônio 02 = w22 = -0.577)------></BR>
x2-------(sinapse/peso W( x2, neurônio 03 = w23 = -0.469)------>


In [99]:
pesos_neuronio_camada = np.array([[-0.017],[-0.893],[0.148]])

A variavel "pesos_neuronio_camada" (matriz) contém os pesos (W) de ligação dos neurônios da camada oculta para o neurônio de saída.

neurônio 01 ------(sinapse/peso W ( neurônio 01, neurônio de saída = w1s = -0.017)------>
<BR>neurônio 02 ------(sinapse/peso W ( neurônio 02, neurônio de saída = w2s = -0.893)------></BR>
neurônio 03 ------(sinapse/peso W ( neurônio 03, neurônio de saída = w3s = 0.148)------>

In [141]:
pesos0 = 2*np.random.random((2,3)) - 1
pesos1 = 2*np.random.random((3,1)) - 1

momento = 1
taxa_aprendizagem = 0.3

Utilidade da variavel "momento":

Escapar de mínimos locais (nem sempre funciona)

Define o quão confiável é a última alteração

Alto: aumenta a velocidade da convergência

Baixo: pode evitar mínimos locais
<BR></BR>

Utilidade da variavel "Taxa de aprendizagem" (learning rate)

Define quão rápido o algoritmo vai aprender

Alto: a convergência é rápida mas pode perde o mínimo global

Baixo: será mais lento mas tem mais chances de chegar no mínimo global

In [101]:
rodadas_ajuste_peso=1

for j in range (rodadas_ajuste_peso):

SyntaxError: incomplete input (2113301295.py, line 3)

A variavel "rodadas_ajuste_peso" é o número de vezes que os pesos vão ser atualizados (reajustados), com objetivo de termos o menor erro na rede neuoral.

In [102]:
    camada_entrada = entradas
    soma_sinapse1 = np.dot(camada_entrada, pesos_x1_x2)    

In [103]:
    soma_sinapse1

array([[ 0.   ,  0.   ,  0.   ],
       [ 0.358, -0.577, -0.469],
       [-0.424, -0.74 , -0.961],
       [-0.066, -1.317, -1.43 ]])

A função dot da biblioteca numpy, recebe a camada de neurônios com seus repectivos pesos e faz o somatório dos produtos do valor da ativação (na camada de entrada será os dados de entrada x1/x2 e na camada oculta os valores de ativação do neurônio) com o peso (w) respectivo.

Exemplo:

(x1,x2): (0,0) -> neurônio 01

x1 * w11 + x2 * w21 = somatório dos produtos para neuronio 01

x1 * w12 + x2 * w22 = somatório dos produtos para neuronio 02

x1 * w13 + x2 * w23 = somatório dos produtos para neuronio 03

O mesmo processo é feito para: (0,1), (1,0) e (1,1)

In [104]:
    camada_oculta = sigmoid(soma_sinapse1)

In [105]:
    camada_oculta

array([[0.5       , 0.5       , 0.5       ],
       [0.5885562 , 0.35962319, 0.38485296],
       [0.39555998, 0.32300414, 0.27667802],
       [0.48350599, 0.21131785, 0.19309868]])

Neste momento é utilizado a função sigmoide para gerar a camada oculta para cada registro: (0,0), (0,1), (1,0), (1,1)

In [106]:
    soma_sinapse2 = np.dot(camada_oculta, pesos_neuronio_camada)    

In [107]:
    soma_sinapse2

array([[-0.381     ],
       [-0.27419072],
       [-0.25421887],
       [-0.16834784]])

A função dot da biblioteca numpy, recebe os neurônios da camada oculta com seus repectivos pesos (w) e faz o somatório dos produtos do valor da ativação (a) pelo peso (w).

Exemplo:

(0,0) -> neurônio de saída

a1 * w1s + a2 * w2s + a3 * w3s  = somatório dos produtos para neuronio saida

O mesmo processo é feito para: (0,1), (1,0) e (1,1)

In [108]:
    camada_saida = sigmoid(soma_sinapse2)

In [109]:
    camada_saida

array([[0.40588573],
       [0.43187857],
       [0.43678536],
       [0.45801216]])

Neste momento é utilizado a função sigmoide para gerar o valor de ativação (a) do neurôni de saída para cada registro: (0,0), (0,1), (1,0), (1,1)

In [110]:
    erro = respostas_esperadas - camada_saida

In [111]:
    erro

array([[-0.40588573],
       [ 0.56812143],
       [ 0.56321464],
       [-0.45801216]])

In [112]:
    respostas_esperadas

array([[0],
       [1],
       [1],
       [0]])

A variavel erro como o proprio nome diz armazena o erro de todos os registro (0,0), (0,1), (1,0), (1,1).

É feito a subtração dos valores esperados com os valores encontrados da camada de saída (valor de ativação do neurônio) 

In [113]:
    media_erro_absoluto = np.mean(np.abs(erro))

In [114]:
    print('Erro : '+ str(media_erro_absoluto))

Erro : 0.49880848923713045


In [115]:
    media_erro_absoluto 

0.49880848923713045

Neste momento fazemos a média dos erros desconsiderando o valor negativo dos erros e armazenamos na variavel "media_erro_absoluto"

A função abs nos da o valor absoluto (valor do algarismo, independentemente do lugar que ocupa).

A função mean nos da a média.

Quando falamos que a média do erro na rede neuoral é igual é 0,49 (media_erro_absoluto) estamos dizendo que nossa rede tem 49% de erro e 51% de precisão (resultado para uma rodada). É preciso ser feito mais rodadas de ajustes de pesos para que a média dos erros seja a menor possivel.

In [116]:
    derivada_saida = derivadaParcial(camada_saida)

    delta_saida = erro * derivada_saida

In [117]:
    camada_saida

array([[0.40588573],
       [0.43187857],
       [0.43678536],
       [0.45801216]])

In [118]:
    derivada_saida

array([[0.2411425 ],
       [0.24535947],
       [0.24600391],
       [0.24823702]])

In [119]:
    delta_saida

array([[-0.0978763 ],
       [ 0.13939397],
       [ 0.138553  ],
       [-0.11369557]])

A formala para calcular o delta na camada oculta é diferente, do que foi feito na camada de saída.

fórmula:

Delta da camada oculta  = valor de ativação do neurônio * peso (da camada oculta para a camada de saída) * delta de saída 

Para podemos fazer a multiplicação do peso com delta de saida é preciso primeiro gerar a matriz transporta da variavel "pesos_neuronio_camada"(matriz).

obs: Define-se como matriz transposta uma matriz qualquer resultante da troca ordenada das linhas pelas colunas de uma matriz chamada de original.

In [120]:
    matriz_transposta_pesos_neuronio_camada = pesos_neuronio_camada.T

In [121]:
    pesos_neuronio_camada

array([[-0.017],
       [-0.893],
       [ 0.148]])

In [122]:
    matriz_transposta_pesos_neuronio_camada

array([[-0.017, -0.893,  0.148]])

após gerar a matriz transposta (variavel "matriz_transposta_pesos_neuronio_camada") podemos fazer a multiplicação com delta de saida ( variavel "delta_saida").

In [123]:
    deltaSaida_X_Peso = delta_saida.dot( matriz_transposta_pesos_neuronio_camada)

In [124]:
    deltaSaida_X_Peso

array([[ 0.0016639 ,  0.08740354, -0.01448569],
       [-0.0023697 , -0.12447882,  0.02063031],
       [-0.0023554 , -0.12372783,  0.02050584],
       [ 0.00193282,  0.10153015, -0.01682694]])

In [125]:
    delta_oculta = deltaSaida_X_Peso *  derivadaParcial(camada_oculta)

In [126]:
    delta_oculta

array([[ 0.00041597,  0.02185088, -0.00362142],
       [-0.00057384, -0.02866677,  0.00488404],
       [-0.00056316, -0.02705587,  0.00410378],
       [ 0.00048268,  0.01692128, -0.00262183]])

Após acharmos o produto (deltaSaida_X_Peso) do peso (da camada oculta para a camada de saída) pelo delta de saída, multiplicamos o resultado pela derivada parcial do valor de ativação do neurônio da camada oculta (sigmoide).
  
Fórmula:
Delta da camada oculta  = valor de ativação do neurônio * peso (da camada oculta para a camada de saída) * delta de saída 

-----------------------------------------------------------------------------------------------------------------------------

Calculada os deltas e tendo os valores de ativação dos neurônios da camada oculta e camada de saida é possivel agora fazer o ajustes dos pesos, seguindo a formula abaixo:

novo peso = ( peso atual ∗ 𝑚𝑜𝑚𝑒𝑛𝑡𝑜 ) + ( ed ∗ 𝑡𝑎𝑥𝑎 𝑑𝑒 𝑎𝑝𝑟𝑒𝑛𝑑𝑖𝑧𝑎𝑔𝑒𝑚)

"ed" é dados pela fórmula:

ed = 𝑒𝑛𝑡𝑟𝑎𝑑𝑎 ∗ 𝑑𝑒𝑙𝑡𝑎

A variavel "entrada" e "delta" é respectivamente o valor de ativação e o delta que achamaos para cada neurônio da camada oculta e camada de saída.

Utilidade da variavel "momento":

Escapar de mínimos locais (nem sempre funciona)

Define o quão confiável é a última alteração

Alto: aumenta a velocidade da convergência

Baixo: pode evitar mínimos locais

Utilidade da variavel "Taxa de aprendizagem" (learning rate)

Define quão rápido o algoritmo vai aprender

Alto: a convergência é rápida mas pode perde o mínimo global

Baixo: será mais lento mas tem mais chances de chegar no mínimo global

-------------------------------------------------------------------------------------------

Os pesos serão ajustado seguindo a ordem abaixo (backpropagation):

1° pesos ajustados -> pesos da camada oculta para a camada de saída.

2° pesos ajustados -> pesos da camada de entrada para a camada de saída.


Para calcularmos: ed = 𝑒𝑛𝑡𝑟𝑎𝑑𝑎 ∗ 𝑑𝑒𝑙𝑡𝑎

Somatório dos produtos entre "dados de entrada" (camada oculta = valor de ativação | camada de entrada = dados de entrada)  com o delta dos respectivos neurônias de resgistro: (0,0), (0,1), (1,0) e (1,1). Para isso é preciso ser feito a matriz trasposta da camada.

In [127]:
    camada_oculta

array([[0.5       , 0.5       , 0.5       ],
       [0.5885562 , 0.35962319, 0.38485296],
       [0.39555998, 0.32300414, 0.27667802],
       [0.48350599, 0.21131785, 0.19309868]])

Na variavel "camada_oculta" temos:

linha 1 = neurônio 01, 02 e 03 com seus respecitivos valores de ativação para o registro (0,0)

linha 2 = neurônio 01, 02 e 03 com seus respecitivos valores de ativação para o registro (0,1)

linha 3 = neurônio 01, 02 e 03 com seus respecitivos valores de ativação para o registro (1,0)

linha 4 = neurônio 01, 02 e 03 com seus respecitivos valores de ativação para o registro (1,1)

In [128]:
    camada_oculta_transposta = camada_oculta.T

A variavel "camada_oculta_transposta" recebe a matriz transposta da variavel "camada_oculta".

In [129]:
    camada_oculta_transposta

array([[0.5       , 0.5885562 , 0.39555998, 0.48350599],
       [0.5       , 0.35962319, 0.32300414, 0.21131785],
       [0.5       , 0.38485296, 0.27667802, 0.19309868]])

Na matriz "camada_oculta_transposta" temos:

na linha 1 = são os neurônios 01 de cada resgistro (0,0), (0,1), (1,0) e (1,1).

na linha 2 = são os neurônios 02 de cada resgistro (0,0), (0,1), (1,0) e (1,1).

na linha 3 = são os neurônios 03 de cada resgistro (0,0), (0,1), (1,0) e (1,1).

É feito um agrupamento dos neurônios.

In [140]:
delta_saida

array([[-0.0978763 ],
       [ 0.13939397],
       [ 0.138553  ],
       [-0.11369557]])

In [130]:
    novo_peso_saida = camada_oculta_transposta.dot(delta_saida)

In [131]:
    pesos_neuronio_camada = (pesos_neuronio_camada * momento) + (novo_peso_saida * taxa_aprendizagem )

In [132]:
    pesos_neuronio_camada

array([[-0.00711903],
       [-0.88642447],
       [ 0.15432644]])

In [133]:
    entradas

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

A variavel "entradas" (matriz) contém os dados de entrada "x1" e "x2". A variaval "resposta_esperada" (matriz) é valor da "classe" para determinado dado de entrada "x1" e "x2".

|x1 x2| -> classe
| 0 0 | -> 0
| 0 1 | -> 1
| 1 0 | -> 1
| 1 1 | -> 0

In [134]:
    camada_entrada_transposta = entradas.T

In [135]:
    camada_entrada_transposta

array([[0, 0, 1, 1],
       [0, 1, 0, 1]])

Na matriz "camada_entrada_transposta" temos:

na linha 1 = são os x1 dos resgistros de entrada: (0,0), (0,1), (1,0) e (1,1).

na linha 2 = são os x2 dos resgistros de entrada: (0,0), (0,1), (1,0) e (1,1).

In [139]:
delta_oculta

array([[ 0.00041597,  0.02185088, -0.00362142],
       [-0.00057384, -0.02866677,  0.00488404],
       [-0.00056316, -0.02705587,  0.00410378],
       [ 0.00048268,  0.01692128, -0.00262183]])

In [136]:
    novo_peso_entrada = camada_entrada_transposta.dot(delta_oculta)

In [137]:
    pesos_x1_x2 = (pesos_x1_x2 * momento) + (novo_peso_entrada * taxa_aprendizagem )

In [138]:
    pesos_x1_x2 

array([[-0.42402414, -0.74304038, -0.96055542],
       [ 0.35797265, -0.58052365, -0.46832134]])